### ISSUE TITLE
Maven Build Failure , cannot reach com.asciidocfx.pty4j

### ISSUE THREAD

**Issue by NickYadance** [rahmanusta/cloudterm#1]
Info here :

> [ERROR] Failed to execute goal on project cloudterm: Could not resolve dependencies for project com.example:cloudterm:jar:0.0.1-SNAPSHOT: Could not find artifact com.asciidocfx.pty4j:pty4j:jar:0.7.3 in rahmanusta-releases (http://asciidocfx.com/build) -> [Help 1]

emmm.... wondering what's wrong

**Comment by rahmanusta** [comment]
Just updated the dependency repository for pty4j, can you build it with new commit?
